spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbis-postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: false