version: "3"

services:
  postgresql:
    image: postgres:16.0
    container_name: dbis-postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=dbis-exercise"